pipeline{
    agent any
    stages{
        stage('Build'){
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Simulando un despliegue a un servidor de aplicaciones'
            }
        }
    }

    post{
        always{
            echo 'siempre se ejecutara'
        }
        success{
            echo 'Se ejecuta si todo pasa correctamente'
        }
        failure{
            echo 'Se ejecuta si algo falla en nuestro pipeline'
        }
    }
}